# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_param simulator.modelsimInstallPath D:/SoftPath/modelsim/win64
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.cache/wt [current_project]
set_property parent.project_path D:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
add_files d:/Projects/CompArch/CPU-Nyarlathotep/mips_54_mars_board_switch_student.coe
add_files d:/Projects/CompStruct/SuperCyclone2/Apoclyps.coe
add_files -quiet d:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.srcs/sources_1/ip/clk_generator/clk_generator.dcp
set_property used_in_implementation false [get_files d:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.srcs/sources_1/ip/clk_generator/clk_generator.dcp]
add_files -quiet d:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.srcs/sources_1/ip/root_cluster/root_cluster.dcp
set_property used_in_implementation false [get_files d:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.srcs/sources_1/ip/root_cluster/root_cluster.dcp]
add_files -quiet d:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.srcs/sources_1/ip/DMEM/DMEM.dcp
set_property used_in_implementation false [get_files d:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.srcs/sources_1/ip/DMEM/DMEM.dcp]
add_files -quiet d:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.srcs/sources_1/ip/IMEM/IMEM.dcp
set_property used_in_implementation false [get_files d:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.srcs/sources_1/ip/IMEM/IMEM.dcp]
read_verilog {
  D:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.srcs/sources_1/new/aluHeader.vh
  D:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.srcs/sources_1/new/sdHeader.vh
  D:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.srcs/sources_1/new/blStates.vh
  D:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.srcs/sources_1/new/sdStates.vh
  D:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.srcs/sources_1/new/knStates.vh
}
read_verilog -library xil_defaultlib {
  D:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.srcs/sources_1/new/DIV_simplified.v
  D:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.srcs/sources_1/new/CLZAlgorithm.v
  D:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.srcs/sources_1/new/MULT_simplified.v
  D:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.srcs/sources_1/new/CP0.v
  D:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.srcs/sources_1/new/extender.v
  D:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.srcs/sources_1/new/ALU.v
  D:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.srcs/sources_1/new/regfile.v
  D:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.srcs/sources_1/new/bootloader.v
  D:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.srcs/sources_1/new/vga.v
  D:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.srcs/sources_1/new/spi_controller.v
  D:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.srcs/sources_1/new/sd_controller.v
  D:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.srcs/sources_1/new/kernel.v
  D:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.srcs/sources_1/new/freqDivider.v
  D:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.srcs/sources_1/new/Supercyclone.v
  D:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.srcs/sources_1/new/debugInfo.v
  D:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.srcs/sources_1/new/computer.v
  D:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.srcs/sources_1/new/7seg-display.v
  D:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.srcs/sources_1/new/topmodule.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.srcs/constrs_1/new/supercyclone_top.xdc
set_property used_in_implementation false [get_files D:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.srcs/constrs_1/new/supercyclone_top.xdc]


synth_design -top topmodule -part xc7a100tcsg324-1


write_checkpoint -force -noxdef topmodule.dcp

catch { report_utilization -file topmodule_utilization_synth.rpt -pb topmodule_utilization_synth.pb }
