onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /computer_forsim_tb/reset
add wave -noupdate /computer_forsim_tb/cpuEna
add wave -noupdate /computer_forsim_tb/clk_cpu
add wave -noupdate /computer_forsim_tb/inst
add wave -noupdate /computer_forsim_tb/pc
add wave -noupdate /computer_forsim_tb/cpuRunning
add wave -noupdate /computer_forsim_tb/cpuPaused
add wave -noupdate /computer_forsim_tb/uut/sccpu/cpuStarted
add wave -noupdate /computer_forsim_tb/uut/sccpu/cp0Cause
add wave -noupdate /computer_forsim_tb/uut/sccpu/cp0Exception
add wave -noupdate /computer_forsim_tb/uut/sccpu/cp0ExecAddr
add wave -noupdate /computer_forsim_tb/uut/sccpu/cp0Intr
add wave -noupdate /computer_forsim_tb/uut/sccpu/cp0RData
add wave -noupdate /computer_forsim_tb/uut/sccpu/cp0Status
add wave -noupdate /computer_forsim_tb/uut/sccpu/aluA
add wave -noupdate /computer_forsim_tb/uut/sccpu/aluB
add wave -noupdate /computer_forsim_tb/uut/sccpu/aluModeSel
add wave -noupdate /computer_forsim_tb/uut/sccpu/aluR
add wave -noupdate /computer_forsim_tb/uut/sccpu/aluRX
add wave -noupdate /computer_forsim_tb/uut/sccpu/bubbleEX
add wave -noupdate /computer_forsim_tb/uut/sccpu/bubbleID
add wave -noupdate /computer_forsim_tb/uut/sccpu/bubbleIF
add wave -noupdate /computer_forsim_tb/uut/sccpu/bubbleMEM
add wave -noupdate /computer_forsim_tb/uut/sccpu/bubbleWB
add wave -noupdate /computer_forsim_tb/uut/sccpu/allowEX
add wave -noupdate /computer_forsim_tb/uut/sccpu/allowID
add wave -noupdate /computer_forsim_tb/uut/sccpu/allowIF
add wave -noupdate /computer_forsim_tb/uut/sccpu/allowMEM
add wave -noupdate /computer_forsim_tb/uut/sccpu/allowWB
add wave -noupdate /computer_forsim_tb/uut/sccpu/instCounter
add wave -noupdate /computer_forsim_tb/uut/sccpu/bubbleCounter
add wave -noupdate /computer_forsim_tb/uut/sccpu/slotCounter
add wave -noupdate /computer_forsim_tb/uut/sccpu/preif_pc
add wave -noupdate /computer_forsim_tb/uut/sccpu/if_invalidated_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/if_npc_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/ifid_inst
add wave -noupdate /computer_forsim_tb/uut/sccpu/id_itype_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/id_aluA_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/id_aluB_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/id_aluModeSel_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/id_condJump_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/id_dmemEn_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/id_dmemWe_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/id_npc_cp0Val_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/id_npc_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/id_rfWAddr_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/id_rfWe_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/id_rs_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/id_rt_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/id_rsVal_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/id_rtVal_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/id_rs_willRead_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/id_rt_willRead_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/id_syscallFuncode_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/idex_itype
add wave -noupdate /computer_forsim_tb/uut/sccpu/idex_aluA
add wave -noupdate /computer_forsim_tb/uut/sccpu/idex_aluB
add wave -noupdate /computer_forsim_tb/uut/sccpu/idex_aluModeSel
add wave -noupdate /computer_forsim_tb/uut/sccpu/idex_condJump
add wave -noupdate /computer_forsim_tb/uut/sccpu/idex_dmemEn
add wave -noupdate /computer_forsim_tb/uut/sccpu/idex_dmemWe
add wave -noupdate /computer_forsim_tb/uut/sccpu/idex_rfWAddr
add wave -noupdate /computer_forsim_tb/uut/sccpu/idex_rfWe
add wave -noupdate /computer_forsim_tb/uut/sccpu/idex_rtVal
add wave -noupdate /computer_forsim_tb/uut/sccpu/ex_aluA_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/ex_aluB_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/ex_aluModeSel_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/ex_bytePos_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/ex_condJump_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/ex_dmemEn_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/ex_dmemIn_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/ex_dmemWe_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/ex_extra_result_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/ex_imm_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/ex_itype_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/ex_rd_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/ex_result_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/ex_rfWAddr_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/ex_rfWe_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/ex_rsVal_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/ex_rs_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/ex_rtVal_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/ex_rt_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/exmem_bytePos
add wave -noupdate /computer_forsim_tb/uut/sccpu/exmem_condJump
add wave -noupdate /computer_forsim_tb/uut/sccpu/exmem_itype
add wave -noupdate /computer_forsim_tb/uut/sccpu/exmem_result
add wave -noupdate /computer_forsim_tb/uut/sccpu/exmem_rfWAddr
add wave -noupdate /computer_forsim_tb/uut/sccpu/exmem_rfWe
add wave -noupdate /computer_forsim_tb/uut/sccpu/mem_bytePos_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/mem_condJump_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/mem_dmemOut_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/mem_itype_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/mem_result_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/mem_rfWAddr_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/mem_rfWe_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/memwb_itype
add wave -noupdate /computer_forsim_tb/uut/sccpu/memwb_result
add wave -noupdate /computer_forsim_tb/uut/sccpu/memwb_rfWAddr
add wave -noupdate /computer_forsim_tb/uut/sccpu/memwb_rfWe
add wave -noupdate /computer_forsim_tb/uut/sccpu/wb_itype_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/wb_result_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/wb_rfWAddr_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/wb_rfWe_wire
add wave -noupdate /computer_forsim_tb/uut/sccpu/rfRAddr1
add wave -noupdate /computer_forsim_tb/uut/sccpu/rfRAddr2
add wave -noupdate /computer_forsim_tb/uut/sccpu/rfRData1
add wave -noupdate /computer_forsim_tb/uut/sccpu/rfRData2
add wave -noupdate /computer_forsim_tb/uut/sccpu/rfWAddr
add wave -noupdate /computer_forsim_tb/uut/sccpu/rfWData
add wave -noupdate /computer_forsim_tb/uut/sccpu/rfWe
add wave -noupdate /computer_forsim_tb/uut/sccpu/hi
add wave -noupdate /computer_forsim_tb/uut/sccpu/lo
add wave -noupdate /computer_forsim_tb/uut/dmem/inst/native_mem_module/blk_mem_gen_v8_3_3_inst/memory
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {107381666 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 365
configure wave -valuecolwidth 120
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {210 us}
