# 
# Synthesis run script generated by Vivado
# 

set_param simulator.modelsimInstallPath D:/SoftPath/modelsim/win64
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.cache/wt [current_project]
set_property parent.project_path D:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
read_ip -quiet d:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.srcs/sources_1/ip/root_cluster/root_cluster.xci
set_property is_locked true [get_files d:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.srcs/sources_1/ip/root_cluster/root_cluster.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top root_cluster -part xc7a100tcsg324-1 -mode out_of_context

rename_ref -prefix_all root_cluster_

write_checkpoint -force -noxdef root_cluster.dcp

catch { report_utilization -file root_cluster_utilization_synth.rpt -pb root_cluster_utilization_synth.pb }

if { [catch {
  file copy -force D:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.runs/root_cluster_synth_1/root_cluster.dcp d:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.srcs/sources_1/ip/root_cluster/root_cluster.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub d:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.srcs/sources_1/ip/root_cluster/root_cluster_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub d:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.srcs/sources_1/ip/root_cluster/root_cluster_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim d:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.srcs/sources_1/ip/root_cluster/root_cluster_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim d:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.srcs/sources_1/ip/root_cluster/root_cluster_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir D:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.ip_user_files/ip/root_cluster]} {
  catch { 
    file copy -force d:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.srcs/sources_1/ip/root_cluster/root_cluster_stub.v D:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.ip_user_files/ip/root_cluster
  }
}

if {[file isdir D:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.ip_user_files/ip/root_cluster]} {
  catch { 
    file copy -force d:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.srcs/sources_1/ip/root_cluster/root_cluster_stub.vhdl D:/Projects/CompStruct/SuperCyclone2/SuperCyclone2.ip_user_files/ip/root_cluster
  }
}
